CREATE TABLE dogecart (
  id SERIAL PRIMARY KEY,
  dogeuser_id INTEGER NOT NULL,
  pid INTEGER NOT NULL,
  brand VARCHAR(100) NOT NULL,
  flavor VARCHAR(100) NOT NULL,
  price INTEGER NOT NULL,
  image VARCHAR(100) NOT NULL,
  quantity INTEGER NOT NULL
);